### ISSUE TITLE
Why is this needed

### ISSUE THREAD

**Issue by GGWarriorWP** [jredfox/iitemrenderer#14]
Hi,
just interested why bring back an old system from 1.7 to 1.12 when people in large forums say that there are much better and performant solutions in 1.12, and even if you need a dynamic model, there are solutions for this as well in 1.12.
So please tell me an actual usecase of this mod, as I don't see any, and I am really interested to learn more about modding.

**Comment by GGWarriorWP** [comment]
Sorry I missed the readme, it is now clear to me

**Comment by jredfox** [comment]
how does the README.MD make it any more clear. the curseforge forum specifically says why it is needed. The main reason is because forge broke their own system with items wanting to replace current render for an item that isn't theirs, several other major issues, as well as forcing the TEISR thing when not all dynamic items have a TE to begin with. 

The other major thing is the preset open gl transforms from 1.7.10 don't exist in current versions thus the older renderers are incompatible with the newer system since the presets are not there also an issue with the current IItemRenderer and help is needed in fixing it.

This is explained better on curseforge
https://minecraft.curseforge.com/projects/iitemrenderer-reborn
